---
- name: Playbook to check periodically WoD api-db
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure that this a compliant WoD system
      ansible.builtin.include_tasks: "{{ ANSIBLEDIR }}/check_system.yml"

    - name: Setup ufw firewall TCP rules
      become: true
      become_user: root
      community.general.ufw:
        rule: allow
        port: "{{ WODAPIDBPORT }}"
        proto: tcp
        state: enabled
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version >= "20"

    - name: Setup firewalld TCP rules
      become: true
      become_user: root
      ansible.posix.firewalld:
        port: "{{ WODAPIDBPORT }}/tcp"
        permanent: true
        state: enabled
      when:
        - ansible_distribution == "CentOS" or ansible_distribution == "Rocky"

    - name: Enable WoD services
      become: true
      become_user: root
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        enabled: true
        name: "{{ item }}"
      with_items:
        - docker

    - name: Test private tasks YAML file
      ansible.builtin.command: ls "{{ ANSIBLEPRIVDIR }}/check_api-db.yml"
      register: acj_path
      failed_when: false
      changed_when: false

    - name: Now call private tasks if available
      ansible.builtin.include_tasks: "{{ ANSIBLEPRIVDIR }}/check_api-db.yml"
      when:
        - acj_path.rc == 0
