---
- hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: System details
      ansible.builtin.shell: echo '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}' > '{{ ansible_env.HOME }}/.mail/distrib'
