---


  - name: Add EPEL repository into repo list
    become: yes
    become_user: root
    yum:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
      state: present
    when:
      - ansible_distribution == "CentOS" 

  - name: Add EPEL repository into repo list
    become: yes
    become_user: root
    yum:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
      disable_gpg_check: true
      state: present
    when:
      - ansible_distribution == "RedHat"


  - name: Disable Podman service
    register: service_stop
    become: yes
    become_user: root
    failed_when:
      - '"Could not find the requested service" not in service_stop.stdout'
      - service_stop.rc != 0
    systemd:
      state: stopped
      enabled: no
      name: podman
    ignore_errors: true

  - name: Ensure all required packages are installed
    become: yes
    become_user: root
    package:
      name:
      - podman
      - podman-compose
      state: present

  - name: Enable Podman service
    become: yes
    become_user: root
    systemd:
      state: started
      daemon_reload: yes
      enabled: yes
      name: podman

  - name: Ensure "{{ WODUSER }}" user belong to the Podman group
    become: yes
    become_user: root
    user:
      name: "{{ WODUSER }}"
      state: present
      append: yes
      groups: "podman"
