---
- name: Playbook for WoD api-db server installation
  hosts: all
  gather_facts: true

  tasks:
    - name: Include variables for the underlying distribution
      ansible.builtin.include_vars: "{{ ANSIBLEDIR }}/group_vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

    - name: Base setup for a base system
      ansible.builtin.include_tasks: "{{ ANSIBLEDIR }}/install_base_system.yml"

    - name: Setup first the Docker context (packages, deps, ...)
      ansible.builtin.include_tasks: "{{ ANSIBLEDIR }}/install_docker.yml"

    - name: Ensure all required packages are installed
      become: true
      become_user: root
      ansible.builtin.package:
        name:
          - ansible
          - python3
          - python3-pip
          - git
          - rsync
          - wget
          - bzip2
          - jq
          - moreutils
          - net-tools
          - nodejs
          - npm
          - telnet
          - man
          - unzip
          - netcat
        update_cache: true
        state: present

    - name: Ensure all required DEB packages are installed
      become: true
      become_user: root
      ansible.builtin.apt:
        pkg:
          - apt-file
          - ldap-utils
          - fail2ban
          - libproc-processtable-perl
          - acct
          - libjson-perl
          - libyaml-tiny-perl
          - postgresql-client
      when:
        - ansible_os_family == "Debian"

    - name: Ensure all required RPM packages are installed
      become: true
      become_user: root
      ansible.builtin.package:
        pkg:
          - openldap-clients
          - perl-Crypt-PasswdMD5
          - fail2ban-all
          - perl-Proc-ProcessTable
          - perl-Data-Dumper
          - psacct
          - perl-JSON
          - perl-YAML-Tiny
          - postgresql
      when:
        - ansible_distribution == "CentOS" or ansible_distribution == "Rocky"

    - name: Ensure all required pip packages are installed
      become: true
      become_user: root
      ansible.builtin.pip:
        name:
          - yq
        state: present

    - name: Ensure required directories under /usr/local are owned by "{{ WODUSER }}"
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ WODUSER }}"
        group: "{{ WODUSER }}"
        mode: "0755"
      with_items:
        - /usr/local/bin
        - /usr/local/share

    - name: Deliver build-seeders scripts under /usr/local/bin
      become: true
      become_user: root
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /usr/local/bin/{{ item | basename }}
        mode: "0755"
      with_fileglob: ["{{ SCRIPTDIR }}/install/build-seeders.*"]

    - name: Disable WoD services
      become: true
      become_user: root
      ansible.builtin.systemd:
        state: stopped
        daemon_reload: true
        enabled: false
        name: "{{ item }}"
      ignore_errors: true
      register: ignore_errors_register
      with_items:
        - wod-kill-processes

    - name: Find WoD api-db branded files
      ansible.builtin.find:
        paths: "{{ WODAPIDBDIR }}"
        file_type: file
        use_regex: yes
        patterns: ['^.*.j2$']
        recurse: true
      register: apidbtemplates

    - name: Copy WoD api-db branded files as ansible template for variable expansion
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ item | regex_replace('\.j2$') }}"
        mode: "0644"
      with_items: "{{ apidbtemplates.files }}"

    - name: Copy WoD service file as ansible template for variable expansion
      become: true
      become_user: root
      ansible.builtin.template:
        src: "{{ item }}"
        dest: /etc/systemd/system/{{ item | basename | regex_replace('\.j2$') }}
        mode: "0644"
      with_fileglob: ["{{ WODBEDIR }}/sys/wod-*.service.j2"]

    - name: Enable WoD service
      become: true
      become_user: root
      ansible.builtin.systemd:
        state: started
        daemon_reload: true
        enabled: true
        name: "{{ item }}"
      with_items:
        - wod-kill-processes

    - name: Setup ansible configuration
      ansible.builtin.copy:
        src: "{{ WODBEDIR }}/.ansible.cfg"
        dest: "{{ ansible_env.HOME }}/.ansible.cfg"
        owner: "{{ WODUSER }}"
        group: "{{ WODUSER }}"
        mode: "0644"

    - name: Configure fail2ban filter
      become: true
      become_user: root
      ansible.builtin.copy:
        src: "{{ WODBEDIR }}/sys/fail2ban.conf"
        dest: /etc/fail2ban/filter.d/jupyterhub.conf
        owner: root
        group: root
        mode: "0644"

    - name: Configure fail2ban jail
      become: true
      become_user: root
      ansible.builtin.copy:
        src: "{{ WODBEDIR }}/sys/fail2ban.jail"
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: "0644"

    - name: Configure fail2ban action
      become: true
      become_user: root
      ansible.builtin.copy:
        src: "{{ WODBEDIR }}/sys/fail2ban.action"
        dest: /etc/fail2ban/action.d/jupyterhub.conf
        owner: root
        group: root
        mode: "0755"

    - name: Enable fail2ban
      become: true
      become_user: root
      ansible.builtin.systemd:
        state: started
        daemon_reload: true
        enabled: true
        name: fail2ban

    - name: Test private tasks YAML file
      ansible.builtin.command: ls "{{ ANSIBLEPRIVDIR }}/install_api-db.yml"
      register: acj_path
      failed_when: false
      changed_when: false

    - name: Now call private tasks if available
      ansible.builtin.include_tasks: "{{ ANSIBLEPRIVDIR }}/install_api-db.yml"
      when:
        - acj_path.rc == 0
