---
- name: Setup Playbook for WKSHP-ML101 appliance
  hosts: "{{ RTARGET | default([]) }}"
  gather_facts: true
  tasks:
    - name: Setup docker based appliance
      ansible.builtin.include_tasks: "{{ ANSIBLEDIR }}/setup_docker_based_appliance.yml"
